FILM_GENRES = [
    ('action', 'Action'),
    ('adventure', 'Adventure'),
    ('animation', 'Animation'),
    ('anime', 'Anime'),
    ('comedy', 'Comedy'),
    ('crime', 'Crime'),
    ('documentary', 'Documentary'),
    ('drama', 'Drama'),
    ('fantasy', 'Fantasy'),
    ('horror', 'Horror'),
    ('musical', 'Musical'),
    ('mystery', 'Mystery'),
    ('other', 'Miscellaneous'),
    ('romance', 'Romance'),
    ('science_fiction', 'Science Fiction'),
    ('thriller', 'Thriller'),
    ('war', 'War'),
    ('western', 'Western'),
]
